### ISSUE TITLE
Wrong value for null date when using FormService.getControl() as FormGroup

### ISSUE THREAD

**Issue by hirnlego** [digitalascetic/ngx-form#1]
I have an entity that contains a null date (`entity.date`). When I do

`entityForm = <FormGroup>this._formService.getControl(entity);`

`entityForm.get('date').value` is equal to today's date instead of null.

If I do

`entityDateControl = this._formService.getControl(entity.date);`

`entityDateControl.value` is equal to null, correctly.

Maybe the method has issues with FormGroup?

**Comment by martinopic** [comment]
Fixed
